### PR TITLE
Fix a bunch of warnings, add initial Github CI

### PR DESCRIPTION
**Pull request by evelikov**
Greetings everyone,

I was looking at some unrelated libva/nvidia-vaapi-driver related issues (regressions/crashes caused by my patches) and noticed that the build is fairly noisy, since I've got bunch of warnings enabled in `CFLAGS`.

Here is a handy MR that fixes them all, alongside a CI file on top so that new don't creep-in.

### CODE REVIEW

**Comment by evelikov** [comment]
Rebased, pulling out the unrelated av1 patch.

**Comment by evelikov** [comment]
The correct incantation of detecting `gnu_printf` seems tricky - hope it's fixed now :crossed_fingers:

**Comment by elFarto** [comment]
Thanks for the patch, that's a lot of clean-up work!

Looks like it's conflicting with your other PRs now that they've been merged. Can you get that cleared up? Then I can get it merged in.

**Comment by elFarto** [comment]
Thanks for that.

**Pull request merged**
