### PR TITLE
Draft: Remove X11 support, device detection rework and fixes

### PR DESCRIPTION
**Pull request by evelikov**
This series drops X11 support - which should be fine since applications would fallback to DRM or Wayland in that case.

The NVD_GPU override support seems fairly borked, with my patches making it better in some areas and worse in others. That said, I'm marking this as draft for now ... still need to:
  - properly test the NVD_GPU path
  - stop passing an ordinal in a bunch of places, instead use CUDevice
  - should probably use the EGLDevice to CUDevice mapping in both backends

### CODE REVIEW

**Comment by evelikov** [comment]
Currently modeset is required across the board - explicitly (checking the ioctl) or implicitly by opening the card/render node. Just that those checks are spread-out so it's hard to judge it is a hard requirement.

**Comment by POMATu** [comment]
sorry i didnt got why you dropping X support. I am still using Xorg and aint gonna migrate to wayland anytime soon. Or is it unrelated?

**Comment by ClearStaff** [comment]
Wayland is broken in my case on GTX1060, doesn't matter if i use GBM or force EGLStreams in Mutter, i always get frame synchronization glitches (reappearing of old frames on screen). So i forced back X11 for now, with this draft will it be possible to use nvidia-vaapi-driver on X11 with DRM enabled or it will be impossible to use on X11 at all? In the second case i see this draft as a regression instead of improvement.

**Comment by evelikov** [comment]
There are few things here to bear in mind:
 - currently we blindly guess which is the Nvidia backed device - sort of works, but overall a bad idea
 - working X11 backend requires a proper `vaPutSurface` - which is missing, so the app can easily misbehave or crash
   - implementing [that API is a no-go](https://github.com/elFarto/nvidia-vaapi-driver/issues/5#issuecomment-1464925144)
 - applications should be working _properly_ with the gbm backend, when if they don't support/want wayland
 
So overall if you're seeing issues with gbm/wayland it's better to engage with the respective projects. If mutter glitches, but plasma is ok - gnome/mutter devs should be made aware...

**Comment by shadywack** [comment]
I understand the technical needs, but moving to Wayland is absolutely not an option nor a consideration for the vast majority of nVidia users.

This effectively blocks nVidia on Wayland https://gitlab.freedesktop.org/xorg/xserver/-/issues/1317

nVidia states that implicit sync comes at too heavy a performance cost overall, and their driver is not architected to meet implicit sync. Thus, nVidia proposes https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/967

The response is, and I may be oversimplifying, "That doesn't help the Mesa drivers out, and the X developers see no reason to merge this change when it only benefits the proprietary driver". Neither side wants to budge, and I refuse to use Xwayland without implicit or explicit sync, as it makes the UI jitter, lag heavily, and the dropped frames make a lot of the applications unusable. Commonly used Electron Apps are not being ported to Wayland anytime soon and Wine/Proton Wayland support is a long ways off, and Steam may never get ported to Wayland. Given the present disparity of application support for Wayland and the continued reliance on Xwayland, without resolution on the implicit or explicit sync situation, Wayland is blocked for nVidia, most people just aren't aware as to "why" yet.

**Comment by evelikov** [comment]
> I understand the technical needs, but moving to Wayland is absolutely not an option nor a consideration for the vast majority of nVidia users.

Nobody is suggesting or implying you should... Perhaps I should put that in block capitals so people don't get confused :sweat_smile:

**Comment by elFarto** [comment]
Well I think this has been open for long enough. I have no reason to get rid of X11 support, as much as this driver has X11 support.

**Pull request closed without merging**
