### PR TITLE
Unbreak build on FreeBSD

### PR DESCRIPTION
**Pull request by jbeich**
Runtime is untested as I lack an NVIDIA GPU. See also https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264027

### CODE REVIEW

**Comment by elFarto** [comment]
Thanks for the patch, however I'm not entirely certain this driver can actually work on freebsd, since it relies on DMA-BUF, which is a Linux only feature, AFAIK.

Without having someone test this patch on freebsd with NVIDIA hardware, I'm not sure it's worth accepting this patch in.

**Comment by jbeich** [comment]
> relies on DMA-BUF, which is a Linux only feature, AFAIK.

[DragonFly](http://github.com/dragonflybsd/dragonflybsd/tree/master/sys/dev/drm/linux_dma-buf.c), [FreeBSD](https://github.com/freebsd/drm-kmod/tree/master/drivers/dma-buf/dma-buf.c) ([also](https://github.com/evadot/drm-subtree/tree/master/drmkpi/drmcompat_dma_buf.c)), [NetBSD](https://github.com/NetBSD/src/blob/trunk/sys/external/bsd/drm2/linux/linux_dma_buf.c) reimplemented DMA-BUF under BSD license when porting MIT-licensed Linux DRM drivers. DMA-BUF with NVIDIA on FreeBSD requires [nvidia-drm.ko](https://forums.freebsd.org/threads/call-for-testing-nvidia-drm-kernel-module.87161/). For example, `mpv --hwdec=vaapi --vo=dmabuf-wayland` works fine on FreeBSD with Intel iGPU.

**Comment by jbeich** [comment]
Oops, using Intel example in a PR for NVIDIA userland driver is kinda pointless unless using PRIME.

**Comment by elFarto** [comment]
Thanks for the patch. I've decided to merge it in as it's fairly self contained. Not sure it'll actually work though.

**Pull request merged**
