### PR TITLE
Update README with X.Org and Wayland config

### PR DESCRIPTION
**Pull request by n0k0m3**
- Add condition needed to use some configs
- Add Wayland env setup

### CODE REVIEW

**Comment by n0k0m3** [comment]
Note: I had (past tense) a wayland setup with SDDM/KDE + NVIDIA, but the issue with electron apps are just too much for me to workaround (Discord, VSCode are the 2 main apps I use and near impossible to get working without massively modifying stuffs), so maybe a disclaimer on how shitty wayland is on NVIDIA

**Comment by Darkspirit** [comment]
MOZ_ENABLE_WAYLAND=1 is already enabled by default for
* Ubuntu Snap, Ubuntu deb package
* Fedora
* https://nightly.mozilla.org (since https://bugzilla.mozilla.org/show_bug.cgi?id=1749174)
  * a proper .desktop file is required on Wayland: https://bugzilla.mozilla.org/show_bug.cgi?id=1751153#c19

Ideally recommend https://nightly.mozilla.org in general.

**Comment by n0k0m3** [comment]
@Darkspirit Thanks for the suggestions.

Idk about `Force Composition Pipeline` needs to be enabled though as I didn't have the problem with 2 setups I'm having

**Comment by Darkspirit** [comment]
Content is still not correct. This PR partly duplicates what is already mentioned in `Reason` or makes it more confusing. ^^

**Pull request closed without merging**
