### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by crimist**
* Update firefox EGL conf to mention direct backend.
* Update direct backend grammar and compatibility list.

### CODE REVIEW

**Comment by elFarto** [comment]
The EGL backend being referred to is Firefox's EGL backend, rather than it's GLX one. Firefox can use this driver's EGL or direct backend without issue.

I do agree that description does need rewording as having a second 'EGL backend' is confusing.

**Comment by crimist** [comment]
Ah I see, I just assumed (and found it true) that the `MOZ_X11_EGL` didn't need to be set with the direct backend.

Would you be open to a little work on the README? I could add a table of contents and clean it up a little.

**Comment by elFarto** [comment]
It's likely that EGL doesn't need to be forced for recent versions of Firefox, as I believe it's now the default. When the library was initially released that wasn't the case.

I would absolutely be open to the README being worked on.

**Comment by crimist** [comment]
What is the minimum NVIDIA driver version required for this package? Probably worth mentioning in the installation section to reduce issues like #136.

**Comment by crimist** [comment]
Nevermind, I see it's 470 or 500 drivers.

**Comment by elFarto** [comment]
Thanks, those changes look good!

**Pull request merged**
